# Generated by Django 5.1.3 on 2024-11-30 11:50
from django.db import migrations


def create_initial_attribute_names(apps, schema_editor):
    AttributeName = apps.get_model('object_finder', 'AttributeName')
    initial_attributes = [
        'material',
        'size',
        'color',
        'texture',
        'location',
        'description',
        'time',
        'hardness',
        'pattern',
        'brand',
        'print',
        'functionality',
        'taste',
        'volume',
        'part-of'
        'width',
        'shape',
        'height',
        'len',
        'year',
        'price',
        'condition',
    ]
    for attr in initial_attributes:
        AttributeName.objects.create(name=attr)


class Migration(migrations.Migration):

    dependencies = [
        # Replace with the actual previous migration
        ('object_finder', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_initial_attribute_names),
    ]
