# Generated by Django 5.1.3 on 2024-12-01 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('object_finder', '0004_comment_anonymous_name_alter_comment_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='is_sold',
            new_name='is_resolved',
        ),
    ]
