# Generated by Django 5.1.3 on 2024-12-01 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('object_finder', '0005_rename_is_sold_post_is_resolved'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='is_resolved',
            new_name='is_solved',
        ),
    ]
